### ISSUE TITLE
Bsplayer add-on error while searching

### ISSUE THREAD

**Issue by otakon87** [realgam3/service.subtitles.bsplayer#1]
Hello, sorry for my bad english, I'm italian. I just installed the kodi's add-on bsplayer but I cannot find any subtitle for my videos. I just get a generic error which says to check the log file. Here's mine, hope you can help me understand what's going wrong. Thank you

http://xbmclogs.com/pq14jebic

**Comment by realgam3** [comment]
Like xbnc it works only with files no streaming support.

Hope it helps

**Comment by realgam3** [comment]
I need to add support for smb and andorid (use an alternative of rarfile).

Thanks :)

**Comment by otakon87** [comment]
I'm using the android version of the bsplayer atm and it works fine. I hope I can use kodi in the future to search for my subtitles. Anyway thanks for your work m8, much appreciated

**Comment by realgam3** [comment]
I will solve it,
BsPlayer blocked my ip for a weird reason, so it's harder to debug.

**Comment by realgam3** [comment]
Please check that the issue solved in the new version (v0.2)...

**Comment by otakon87** [comment]
So, I tried the new version. This time there is no error when I try to search subtitles for a video from a shared folder but there are no results either. It just says "no subtitles found", while the pc version of bsplayer finds dozens of results. 
Am I missing something? Does this add-on requires some setting? Kodi's subtitles settings are at their default version. Thank you for your support

**Comment by realgam3** [comment]
The log file would really help me, Please send me a link.

**Updates:**
**1)** Worked on genymotion with android 5.1 (http://s8.postimg.org/mss03dvb9/xbmc.png)
**2)** Newer version released (**v0.2.1**: I found the problem in non rar files and fixed it).
**3)** **v0.2.1**: Checked on android device with smb + rar and non rar files and worked, you can close the issue.

**Comment by otakon87** [comment]
Thank you man! Now it works like a charm. 
If I may suggest a modification for the next version, it seems it only searches on bsplayer database while the bsplayer program searches on opensubtitles.org and subtitles.com.br too. I'll close the issue now, thank you again for the assistance
