### ISSUE TITLE
Streaming not supported 

### ISSUE THREAD

**Issue by ananias47** [realgam3/service.subtitles.bsplayer#3]
When i am trying to download subs i have this error and no subs found i use genesis for movies and series

**Comment by realgam3** [comment]
It is known,
BSPlayer using hash of the movie on it's api to look for the subtitles...
There's now way to get this hash from genesis or any other streaming plugin,
But as you can see i announced that i will create an api support of opensubtitles that has the option to search subtitles by name then it will work on streams.

Thanks,
Tomer.
