### ISSUE TITLE
doesn't work with kodi 19 matrix

### ISSUE THREAD

**Issue by netfaruk** [realgam3/service.subtitles.bsplayer#5]
doesn't work with kodi 19 matrix

**Comment by Yw0ke** [comment]
yup, bsplayer is the only good service that works for me and now it doesn't :'(

**Comment by Yw0ke** [comment]
A screen of my log ; https://prnt.sc/18e2h2s

**Comment by realgam3** [comment]
Fixed on https://github.com/realgam3/service.subtitles.bsplayer/commit/205c57ac45d377ebec95d8d7371cb5d582152479
