### ISSUE TITLE
Very slow?

### ISSUE THREAD

**Issue by Harvie** [realgam3/service.subtitles.bsplayer#6]
Hello, this plugin seems to be very succesful in searching subtitles, but it takes a long time when compared to other plugins or even bsplayer which is obviously using the same online api as kodi... Any idea why this is?

**Comment by realgam3** [comment]
I saw there was a server sub domain that wasn't available s09 and I removed it,
So it should be solved in https://github.com/realgam3/service.subtitles.bsplayer/commit/205c57ac45d377ebec95d8d7371cb5d582152479
